---

- name: install dependancies
  apt: name={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - apache2
  tags:
    - install

- name: copy config files
  template: src={{ item.src }}
            dest=/etc/apache2/{{ item.dest }}
  with_items:
    - { src: apache2.conf.j2, dest: apache2.conf }
    - { src: app.conf.j2, dest: "sites-available/000.{{ server_name }}.conf" }


- name: deactivate default domain
  raw: a2dissite {{ item }}
  with_items:
    - 000-default.conf

- name: activate domain
  raw: a2ensite {{ item }}
  with_items:
    - "000-{{ server_name }}.conf"
  notify: start apache2
